version = 0.1

[default.global.parameters]
stack_name = "stack-sam-ayano"
region = "ap-northeast-1"

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = [ "CAPABILITY_IAM", "CAPABILITY_NAMED_IAM" ]
confirm_changeset = false
resolve_s3 = true

[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true
template_file = "c:\\Users\\step6\\Documents\\repos\\sam-ayano\\lambda-nodejs22.x\\template.yaml"
dependency_layer = false

  [default.sync.parameters.parameter_overrides]
RAKUTENAPPLICATIONID = "1068366729131324402"

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"
